### ISSUE TITLE
Deprecate in favor of broccoli-lint-eslint

### ISSUE THREAD

**Issue by Turbo87** [makepanic/broccoli-eslint#9]
Since this repo seems to be unmaintained and PRs don't seems to be processed anymore it would be a good idea to officially deprecate it in favor of the active fork at https://github.com/jonathanKingston/broccoli-lint-eslint. 

It might also make sense to allow that fork to publish releases as `broccoli-eslint` on NPM to keep the naming consistent with the corresponding JSHint and JSCS projects.

/cc @jonathanKingston

**Comment by Turbo87** [comment]
@makepanic any comments?

**Comment by jonathanKingston** [comment]
Sorry just seen this as started a new job. Sounds a positive change at
least as I have an interest in giving more people the rights to help etc in
future.

**Comment by Turbo87** [comment]
@makepanic ping

**Comment by Turbo87** [comment]
@makepanic any comments at all on this?!
